<?php
/** @var $this Adabra_Tracking_Block_Abstract */
$properties = $this->getTrackingProperties();
$coreHelper = Mage::helper('core');
?>
<?php if ($this->canShow() && count($properties)) : ?>
    <!-- ADABRA TRACKING ACTION SCRIPT START -->
    <script type="text/javascript">
        <?php foreach ($properties as $property) : ?>
        _sbnaq.push(<?php echo $coreHelper->jsonEncode($this->getPayload($property['key'], $property['value'])) ?>);
        <?php endforeach; ?>
    </script>
    <!-- ADABRA TRACKING ACTION SCRIPT END -->
<?php endif ?>
